ap_browser_list:
  source: "sql"
  file_path: ''
  file_format: ''
  sql_port: 3306
  sql_user: 'ap_api_ro'
  sql_password: "password"
  replica:
    repl1:
      host: '67.222.111.106'
      priority: 1
    repl2:
      host: '192.40.114.203'
      priority: 2
  db: 'airpush'
  table: 'DELIVERY_browser'
  layout: "hashed"
  attribute:
    name1: 
      name: "browser_name"
      type: "String"
      null_value: ''
    name2: 
      name: "platform"
      type: "UInt16"
      null_value: '0'
    name3: 
      name: "updated_date"
      type: "DateTime"
      null_value: '0000-00-00 00:00:00'
  lifetime_min: 600
  lifetime_max: 900

ap_brandsafe_type:
  source: "file"
  file_path: '/etc/clickhouse-server/brandsafe.tsv'
  file_format: 'CSV'
  sql_port: ''
  sql_user: ''
  sql_password: ''
  layout: "flat"
  attribute:
    name:
      name: "brandsafe_type"
      type: "String"
      null_value: ''
  lifetime_min: 660
  lifetime_max: 900
